### PR TITLE
Demo - Vite + Squint

### PR DESCRIPTION
**Pull request by brandonstubbs**
This is the ported vite vanilla template.

@borkdude There is an issue at the moment with the `#html` reader: https://squint-cljs.github.io/squint/?src=KG5zIG1haW4KICAoOnJlcXVpcmUgWyIuL3N0eWxlLmNzcyJdCiAgICAgICAgICAgIFsiL3ZpdGUuc3ZnJGRlZmF1bHQiIDphcyB2aXRlLWxvZ29dCiAgICAgICAgICAgIFsiLi9jb3VudGVyLmNsanMiIDpyZWZlciBbc2V0dXAtY291bnRlcl1dKSkKCgooc2V0ISAoLi1pbm5lckhUTUwgKGpzL2RvY3VtZW50LnF1ZXJ5U2VsZWN0b3IgIiNhcHAiKSkKICAjaHRtbCBbOmRpdgogICAgICAgICBbOmEgezpocmVmICJodHRwczovL3ZpdGVqcy5kZXYiIDp0YXJnZXQgIl9ibGFuayJ9CiAgICAgICAgICBbOmltZyB7OnNyYyB2aXRlLWxvZ28gOmNsYXNzICJsb2dvIiA6YWx0ICJWaXRlIGxvZ28ifV1dCiAgICAgICAgIDs7IFRPRE8gc3F1aW50IGxvZ28KICAgICAgICAgWzpoMSAiSGVsbG8gVml0ZSEiXQogICAgICAgICBbOmRpdiB7OmNsYXNzICJjYXJkIn0KICAgICAgICAgIFs6YnV0dG9uIHs6aWQgImNvdW50ZXIiIDp0eXBlICJidXR0b24ifV1dCiAgICAgICAgIFs6cCB7OmNsYXNzICJyZWFkLXRoZS1kb2NzIn0KICAgICAgICAgICJDbGljayBvbiB0aGUgVml0ZSBsb2dvIHRvIGxlYXJuIG1vcmUiXV0pCgooc2V0dXAtY291bnRlciAoanMvZG9jdW1lbnQucXVlcnlTZWxlY3RvciAiI2NvdW50ZXIiKSk%3D

There are extra double quotes around everything cause this html to be generated:
image

Will mark this as Draft until resolved

### CODE REVIEW

**Comment by borkdude** [comment]
Bumped squint so this should be fixed

**Comment by brandonstubbs** [comment]
Great this works now

**Comment by borkdude** [comment]
I'm getting:

```
 $ npm run dev

> vanilla@0.0.0 dev
> vite

failed to load config from /Users/borkdude/dev/vite-plugin-squint/demo/vanilla/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /Users/borkdude/dev/vite-plugin-squint/index.mjs
```

**Comment by brandonstubbs** [comment]
@borkdude I can reproduce it. If you run `npm i` at the project root and then go back in that folder it will work. Will open a ticket for this

**Pull request merged**
